scss_files: 'src/stylesheets/**/*.scss'

severity: error

linters:
  LeadingZero:
    style: include_zero
  HexLength:
    style: long
  PropertySortOrder:
    order: smacss
  IdSelector:
    enabled: false
  SelectorFormat:
    convention: 'hyphenated_BEM'
  PlaceholderInExtend:
    enabled: false
